name: Auto Update Content

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # Use the newly created GH_PAT

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set remote URL to SSH
        run: |
          git remote set-url origin git@github.com:dumbolic/dumbolic.github.io.git
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          
      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python update-content.py

      - name: Commit & push
        run: |
          git add content.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "🌀 Auto update content"
            git push
