name: Auto Update Content

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update-content.py  # Ensure this script handles audio file generation or downloading

      - name: Add audio files to commit (if new or updated)
        run: |
          git add audio/quote_audio.mp3
          git add audio/fact_audio.mp3
          git add content.json

      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git commit -m "🔄 Auto-update content" || echo "No changes to commit"
          git push
