name: Auto Update Content

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}  # ✅ This gives push access

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python update-content.py

      - name: Commit & push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add content.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "🌀 Auto update content"
            git push
          fi
